INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('John', 'Travolta', 33);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Vasya', 'Pupkin', 44);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Alice', 'Doe', 55);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Valera', 'Popovets', 22);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Jeck', 'Vorobey', 11);
INSERT INTO USERS (FIRST_NAME, LAST_NAME, AGE)
VALUES ('Ivan', 'Ivanov', 34);

INSERT INTO PRODUCTS (NAME, PRICE, CATEGORY, GENDER, COLOR, PROD_SIZE, COUNT_IN_WAREHOUSE)
VALUES ('Tesla', 100500, 'Car', 'Unisex', 'Red', 'L', 10);
INSERT INTO PRODUCTS (NAME, PRICE, CATEGORY, GENDER, COLOR, PROD_SIZE, COUNT_IN_WAREHOUSE)
VALUES ('Condom', 2, 'First Aid', 'Men', 'Transparent', 'XXL', 1000);
INSERT INTO PRODUCTS (NAME, PRICE, CATEGORY, GENDER, COLOR, PROD_SIZE, COUNT_IN_WAREHOUSE)
VALUES ('Ice Cream', 1, 'Food', 'Unisex', 'White', 'Standard', 10000);
INSERT INTO PRODUCTS (NAME, PRICE, CATEGORY, GENDER, COLOR, PROD_SIZE, COUNT_IN_WAREHOUSE)
VALUES ('Puzzle', 300, 'Games', 'Unisex', 'NA', 'XL', 30);