CREATE TABLE USERS (
    ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(32) NOT NULL,
    LAST_NAME VARCHAR(32) NOT NULL,
    AGE NUMBER
);

CREATE TABLE PRODUCTS (
    ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(32) NOT NULL,
    PRICE NUMBER NOT NULL,
    CATEGORY VARCHAR(32) NOT NULL,
    GENDER VARCHAR(16) NOT NULL,
    COLOR VARCHAR(32) NOT NULL,
    PROD_SIZE VARCHAR(32) NOT NULL,
    COUNT_IN_WAREHOUSE NUMBER
);

-- CREATE TABLE ORDERS (
--     ID NUMBER NOT NULL AUTO_INCREMENT,
--     USER_ID NUMBER NOT NULL,
--     PRIMARY KEY (ID, USER_ID),
--     CONSTRAINT ORDERS_FK FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
-- );
--
-- CREATE TABLE ORDER_PRODUCTS (
--     ORDER_ID NUMBER NOT NULL,
--     PRODUCT_ID NUMBER NOT NULL,
--     PRIMARY KEY (ORDER_ID, PRODUCT_ID),
--     KEY PRODUCT_ID (PRODUCT_ID),
--     CONSTRAINT ORDER_PRODUCTS_FK1 FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID),
--     CONSTRAINT ORDER_PRODUCTS_FK2 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (ID)
-- );
