CREATE TABLE USERS (
    ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(32) NOT NULL,
    LAST_NAME VARCHAR(32) NOT NULL,
    AGE NUMBER
);

CREATE TABLE PRODUCTS (
    ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(32) NOT NULL,
    PRICE NUMBER NOT NULL,
    CATEGORY VARCHAR(32) NOT NULL,
    GENDER VARCHAR(16) NOT NULL,
    COLOR VARCHAR(32) NOT NULL,
    PROD_SIZE VARCHAR(32) NOT NULL,
    COUNT_IN_WAREHOUSE NUMBER
);

CREATE TABLE ORDERS (
    ID NUMBER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER NUMBER NOT NULL,
    STATUS VARCHAR (32) NOT NULL,
    CREATION_DATE DATE
);

CREATE TABLE ORDER_PRODUCT (
    ORDER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL
);
